// Auto-generated by generate_nested_abi_fixture (Rust test in amd_tee_registry_client)
// Nested ABI layout: VerifierJournal { AttestationCore, ShardProof }
//
// Regenerate: cargo test -p amd_tee_registry_client generate_nested_abi_fixture -- --nocapture

use amd_tee_registry::tee_types::{AttestationCore, DecodedJournal, ShardProof, VerificationResult};

pub fn get_fixture_inputs() -> Array<u256> {
    array![
        u256 { low: 0x00000000000000000000000000000020, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000000000e0, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x33333333333333333333333333333333, high: 0x03333333333333333333333333333333 },
        u256 { low: 0x44444444444444444444444444444444, high: 0x04444444444444444444444444444444 },
        u256 { low: 0x0000000000000000000000000000002a, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x0000000000000000000000000000007b, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x55555555555555555555555555555555, high: 0x05555555555555555555555555555555 },
        u256 { low: 0x66666666666666666666666666666666, high: 0x06666666666666666666666666666666 },
        u256 { low: 0x00000000000000000000000000000000, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x0000000000000000000000006553f100, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x00000000000000000000000000000001, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000000000e0, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000000005a0, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x00000000000000000000000000000600, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x00000000000000000000000000000002, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000000004a0, high: 0x00000000000000000000000000000000 },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, high: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa },
        u256 { low: 0x00000000000000000000000000000002, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x11111111111111111111111111111111, high: 0x11111111111111111111111111111111 },
        u256 { low: 0x22222222222222222222222222222222, high: 0x22222222222222222222222222222222 },
        u256 { low: 0x00000000000000000000000000000002, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000deadbeef, high: 0x00000000000000000000000000000000 },
        u256 { low: 0x000000000000000000000000cafebabe, high: 0x00000000000000000000000000000000 },
    ]
}

pub fn get_fixture_expected() -> DecodedJournal {
    let mut raw_report: Array<u32> = array![
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,        0xaaaaaaaa,
    ];

    let certs: Array<u256> = array![
        u256 { low: 0x11111111111111111111111111111111, high: 0x11111111111111111111111111111111 },
        u256 { low: 0x22222222222222222222222222222222, high: 0x22222222222222222222222222222222 },
    ];

    let cert_serials: Array<felt252> = array![
        0xdeadbeef,
        0xcafebabe,
    ];

    DecodedJournal {
        attestation: AttestationCore {
            result: VerificationResult::Success,
            timestamp: 1700000000,
            processor_model: 1,
            raw_report: raw_report.span(),
            certs,
            cert_serials,
            trusted_certs_prefix_len: 2,
        },
        shard: ShardProof {
            storage_commitment: 0x0333333333333333333333333333333333333333333333333333333333333333,
            events_commitment: 0x0444444444444444444444444444444444444444444444444444444444444444,
            fork_block_number: 42,
            end_block_number: 123,
            event_game_contract: 0x0555555555555555555555555555555555555555555555555555555555555555,
            event_shard_id: 0x0666666666666666666666666666666666666666666666666666666666666666,
        },
    }
}

