//! Generate a Cairo test fixture from a VerifierJournal with known values.
//!
//! Run: cargo test -p amd_tee_registry_client generate_nested_abi_fixture -- --nocapture
//!
//! This encodes a VerifierJournal using alloy's ABI encoder (the same encoder
//! the SP1 guest uses) and prints the result as Cairo code ready to paste into
//! `test_journal_decode_fixtures.cairo`.

use alloy_primitives::B256;
use amd_sev_snp_attestation_verifier::stub::{
    AttestationCore, ShardProof, VerificationResult, VerifierJournal,
};

#[test]
fn generate_nested_abi_fixture() {
    // ── Build a VerifierJournal with deterministic test values ───────────

    // 1184-byte raw report (296 u32 words): all 0xAA bytes for easy identification
    let raw_report: Vec<u8> = vec![0xAA; 1184];

    // 2 cert hashes
    let cert_0 = B256::repeat_byte(0x11);
    let cert_1 = B256::repeat_byte(0x22);

    // 2 cert serials (uint160 = 20 bytes, padded to 32 in ABI)
    let serial_0 = alloy_primitives::U160::from(0xDEAD_BEEF_u64);
    let serial_1 = alloy_primitives::U160::from(0xCAFE_BABE_u64);

    let journal = VerifierJournal {
        attestation: AttestationCore {
            result: VerificationResult::Success,
            timestamp: 1700000000,
            processorModel: 1, // Genoa
            rawReport: raw_report.clone().into(),
            certs: vec![cert_0, cert_1],
            certSerials: vec![serial_0, serial_1],
            trustedCertsPrefixLen: 2,
        },
        shard: ShardProof {
            // Use felt252-safe values (< 2^251): zero high byte
            storageCommitment: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x03; b.iter_mut().skip(1).for_each(|x| *x = 0x33); b
            }),
            eventsCommitment: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x04; b.iter_mut().skip(1).for_each(|x| *x = 0x44); b
            }),
            forkBlockNumber: 42,
            endBlockNumber: 123,
            eventGameContract: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x05; b.iter_mut().skip(1).for_each(|x| *x = 0x55); b
            }),
            eventShardId: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x06; b.iter_mut().skip(1).for_each(|x| *x = 0x66); b
            }),
            initialStorageCommitment: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x07; b.iter_mut().skip(1).for_each(|x| *x = 0x77); b
            }),
            forkStateRoot: B256::from_slice(&{
                let mut b = [0u8; 32]; b[0] = 0x01; b.iter_mut().skip(1).for_each(|x| *x = 0x88); b
            }),
        },
    };

    // ── Encode using alloy (same as SP1 guest's output.encode()) ────────
    let encoded = journal.encode();

    // ── Print as Cairo Array<u256> ──────────────────────────────────────
    println!("// Auto-generated by generate_nested_abi_fixture");
    println!("// Nested ABI layout: VerifierJournal {{ AttestationCore, ShardProof }}");
    println!("// Total encoded size: {} bytes ({} u256 words)", encoded.len(), (encoded.len() + 31) / 32);
    println!();

    // Print inputs function
    println!("pub fn get_fixture_inputs() -> Array<u256> {{");
    println!("    array![");
    for chunk in encoded.chunks(32) {
        let mut padded = [0u8; 32];
        let len = chunk.len();
        padded[32 - len..].copy_from_slice(chunk);
        let high = u128::from_be_bytes(padded[0..16].try_into().unwrap());
        let low = u128::from_be_bytes(padded[16..32].try_into().unwrap());
        println!(
            "        u256 {{ low: 0x{:032x}, high: 0x{:032x} }},",
            low, high
        );
    }
    println!("    ]");
    println!("}}");
    println!();

    // Print expected function
    println!("pub fn get_fixture_expected() -> DecodedJournal {{");
    println!("    let mut raw_report: Array<u32> = array![");
    // Raw report is little-endian u32 words in Cairo
    for (i, chunk) in raw_report.chunks(4).enumerate() {
        let word = u32::from_le_bytes(chunk.try_into().unwrap());
        if i > 0 && i % 8 == 0 {
            println!();
        }
        print!("        0x{:08x},", word);
    }
    println!("\n    ];");
    println!();
    println!("    let certs: Array<u256> = array![");
    for cert in &[cert_0, cert_1] {
        let high = u128::from_be_bytes(cert[0..16].try_into().unwrap());
        let low = u128::from_be_bytes(cert[16..32].try_into().unwrap());
        println!(
            "        u256 {{ low: 0x{:032x}, high: 0x{:032x} }},",
            low, high
        );
    }
    println!("    ];");
    println!();
    println!("    let cert_serials: Array<felt252> = array![");
    println!("        0xdeadbeef,");
    println!("        0xcafebabe,");
    println!("    ];");
    println!();
    println!("    DecodedJournal {{");
    println!("        attestation: AttestationCore {{");
    println!("            result: VerificationResult::Success,");
    println!("            timestamp: 1700000000,");
    println!("            processor_model: 1,");
    println!("            raw_report: raw_report.span(),");
    println!("            certs,");
    println!("            cert_serials,");
    println!("            trusted_certs_prefix_len: 2,");
    println!("        }},");
    // Print shard fields from actual encoded values
    println!("        shard: ShardProof {{");
    println!("            storage_commitment: 0x{},", hex::encode(journal.shard.storageCommitment));
    println!("            events_commitment: 0x{},", hex::encode(journal.shard.eventsCommitment));
    println!("            fork_block_number: 42,");
    println!("            end_block_number: 123,");
    println!("            event_game_contract: 0x{},", hex::encode(journal.shard.eventGameContract));
    println!("            event_shard_id: 0x{},", hex::encode(journal.shard.eventShardId));
    println!("            initial_storage_commitment: 0x{},", hex::encode(journal.shard.initialStorageCommitment));
    println!("            fork_state_root: 0x{},", hex::encode(journal.shard.forkStateRoot));
    println!("        }},");
    println!("    }}");
    println!("}}");

    // ── Verify round-trip ───────────────────────────────────────────────
    let decoded = VerifierJournal::decode(&encoded).expect("round-trip decode failed");
    assert_eq!(decoded.attestation.timestamp, 1700000000);
    assert_eq!(decoded.shard.forkBlockNumber, 42);
    assert_eq!(decoded.shard.endBlockNumber, 123);
    assert_eq!(decoded.shard.eventGameContract, journal.shard.eventGameContract);
    assert_eq!(decoded.shard.eventShardId, journal.shard.eventShardId);
    assert_eq!(decoded.shard.initialStorageCommitment, journal.shard.initialStorageCommitment);
    assert_eq!(decoded.shard.forkStateRoot, journal.shard.forkStateRoot);
    println!("\n// Round-trip verification: OK");
}
